batch_size : 32
train_dir : './data'
dictionary_size : 512
sparse_code_size : 256
input_patch_size : 8
out_patch_size : 7
patch_feature : 100
learning_rate : 0.0001
tetta_init : 0.2
epoch : 1000
