batch_size : 64
train_dir : './dataset_train'
dictionary_size : 64
sparse_code_size : 128
input_patch_size : 7
out_patch_size : 5
patch_feature : 100
learning_rate : 1e-4
tetta_init : 0.1
epoch : 1000